"""add_construct_relationship

Revision ID: 3fb9adb1ed3a
Revises: a742776e8948
Create Date: 2025-05-30 04:29:35.821574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fb9adb1ed3a'
down_revision: Union[str, None] = 'a742776e8948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construct_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_construct_links_source', 'construct_links', ['source_id'], unique=False)
    op.create_index('idx_construct_links_source_target', 'construct_links', ['source_id', 'target_id'], unique=False)
    op.create_index('idx_construct_links_target', 'construct_links', ['target_id'], unique=False)
    op.create_table('construct_relationship_fragments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('construct_link_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['construct_link_id'], ['construct_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fragments_construct_link', 'construct_relationship_fragments', ['construct_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fragments_construct_link', table_name='construct_relationship_fragments')
    op.drop_table('construct_relationship_fragments')
    op.drop_index('idx_construct_links_target', table_name='construct_links')
    op.drop_index('idx_construct_links_source_target', table_name='construct_links')
    op.drop_index('idx_construct_links_source', table_name='construct_links')
    op.drop_table('construct_links')
    # ### end Alembic commands ###
