"""add_foreign_key_constraint_to_construct_creator_id

Revision ID: a742776e8948
Revises: f357d69720b4
Create Date: 2025-05-30 02:00:14.336167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a742776e8948'
down_revision: Union[str, None] = 'f357d69720b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'constructs', ['id'])
    op.create_foreign_key(None, 'constructs', 'users', ['creator_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'constructs', type_='foreignkey')
    op.drop_constraint(None, 'constructs', type_='unique')
    # ### end Alembic commands ###
